const { z } = require('zod');

// Worker Request Schema
const WorkerRequestSchema = z.object({
  task_id: z.string().min(1, 'task_id must be a non-empty string'),
  type: z.enum(
    [
      'research',
      'generate_code',
      'review_code',
      'debug',
      'plan',
      'design_schema',
      'write_docs',
      'security_audit',
      'optimize',
      'test',
    ],
    'type must be a valid worker type',
  ),
  agent: z.string().min(1, 'agent must be a non-empty string'),
  goal: z
    .string()
    .min(1, 'goal must be a non-empty string')
    .max(200, 'goal must not exceed 200 characters (keep it to a single, focused sentence)'),
  context: z
    .string()
    .min(1, 'context must be a non-empty string')
    .max(800, 'context must not exceed 800 characters (trim to minimal required context only)'),
  max_retries: z
    .number()
    .int('max_retries must be an integer')
    .min(1, 'max_retries must be at least 1')
    .max(3, 'max_retries must be at most 3')
    .optional()
    .default(3),
  files_attached: z
    .array(z.string())
    .optional()
    .default([])
    .describe('List of file paths to attach to the worker'),
  priority: z
    .enum(['low', 'medium', 'high'])
    .optional()
    .default('medium')
    .describe('Task priority level'),
  confidence_score: z
    .number()
    .int('confidence_score must be an integer')
    .min(0)
    .max(100)
    .optional()
    .describe(
      'Confidence score indicating how confident the agent is in this routing decision (0-100)',
    ),
  metadata: z.record(z.unknown()).optional().describe('Additional metadata for the worker'),
});

// Worker Result Schema
const WorkerResultSchema = z.object({
  task_id: z.string().min(1, 'task_id must be a non-empty string'),
  agent: z.string().min(1, 'agent must be a non-empty string'),
  status: z.enum(
    ['success', 'failure', 'escalate'],
    'status must be one of: success, failure, escalate',
  ),
  output: z
    .string()
    .optional()
    .describe('Output generated by the worker (required for success status)'),
  error: z.string().optional().describe('Error message (required for failure or escalate status)'),
  attempts: z
    .number()
    .int('attempts must be an integer')
    .min(1, 'attempts must be at least 1')
    .optional(),
  duration: z.number().int('duration must be an integer (milliseconds)').optional(),
  findings: z
    .array(z.string())
    .optional()
    .default([])
    .describe('List of findings or issues discovered'),
  suggestions: z
    .array(z.string())
    .optional()
    .default([])
    .describe('List of suggestions or recommendations'),
});

// Swarm Payload Schema
const SwarmPayloadSchema = z.object({
  workers: z
    .array(WorkerRequestSchema)
    .min(1, 'Must have at least one worker')
    .max(28, 'Maximum 28 workers allowed per swarm (for full tribunal)'),
  wave: z
    .enum(['wave-1-core', 'wave-2-security', 'wave-3-domain', 'full'])
    .optional()
    .default('full')
    .describe('Which tribunal wave to execute'),
  tier: z
    .enum(['strategic', 'tactical'])
    .optional()
    .default('tactical')
    .describe('Routing tier: strategic (coordinator spawns sub-swarms) or tactical (leaf agents)'),
  coordinator: z
    .string()
    .optional()
    .describe('The agent responsible for coordinating this swarm tier (e.g. frontend-architect)'),
  shared_context: z
    .record(z.unknown())
    .optional()
    .describe('Context shared between all workers in the swarm'),
  metadata: z
    .record(z.unknown())
    .optional()
    .describe('Additional metadata for the swarm execution'),
});

/**
 * Validate a payload against a Zod schema
 * @param {Object} payload - The payload to validate
 * @param {z.ZodSchema} schema - The Zod schema to validate against
 * @returns {Object} Validation result with { valid: boolean, data?: Object, errors?: Array }
 */
function validatePayload(payload, schema) {
  const result = schema.safeParse(payload);
  if (!result.success) {
    return {
      valid: false,
      errors: result.error.issues.map(issue => ({
        path: issue.path.join('.'),
        message: issue.message,
        code: issue.code,
      })),
    };
  }
  return { valid: true, data: result.data };
}

/**
 * Validate a payload and throw an error if invalid
 * @param {Object} payload - The payload to validate
 * @param {z.ZodSchema} schema - The Zod schema to validate against
 * @throws {Error} If validation fails
 */
function validatePayloadOrThrow(payload, schema) {
  const validationResult = validatePayload(payload, schema);
  if (!validationResult.valid) {
    const errorMessages = validationResult.errors
      .map(err => `${err.path}: ${err.message}`)
      .join('; ');
    throw new Error(`Payload validation failed: ${errorMessages}`);
  }
  return validationResult.data;
}

module.exports = {
  WorkerRequestSchema,
  WorkerResultSchema,
  SwarmPayloadSchema,
  validatePayload,
  validatePayloadOrThrow,
};
